package com.example.ui.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.ArrowBack
import androidx.compose.material.icons.rounded.AutoAwesome
import androidx.compose.material.icons.rounded.CheckCircle
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import com.example.R
import com.example.ui.theme.*
import kotlinx.coroutines.delay

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CustomizationScreen(onBack: () -> Unit) {
    var selectedFurniture by remember { mutableStateOf("Sofa") }
    var selectedStyle by remember { mutableStateOf("Modern") }
    var selectedBudget by remember { mutableStateOf("₹10000 - ₹25000") }
    
    var isGenerating by remember { mutableStateOf(false) }
    var hasGenerated by remember { mutableStateOf(false) }

    val furnitureOptions = listOf("Sofa", "Chair", "Table", "Bed", "Storage")
    val styleOptions = listOf("Modern", "Luxury", "Minimalist", "Scandinavian", "Traditional")
    val budgetOptions = listOf("Under ₹5000", "₹5000 - ₹10000", "₹10000 - ₹25000", "Premium")

    LaunchedEffect(isGenerating) {
        if (isGenerating) {
            delay(2000)
            isGenerating = false
            hasGenerated = true
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Customize Your Room", color = VarnikaText) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Rounded.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = VarnikaPrimary)
            )
        },
        containerColor = VarnikaPrimary,
        bottomBar = {
            if (!hasGenerated && !isGenerating) {
                Surface(color = VarnikaSecondary) {
                    Button(
                        onClick = { isGenerating = true },
                        modifier = Modifier.fillMaxWidth().padding(16.dp).height(56.dp).windowInsetsPadding(WindowInsets.navigationBars),
                        shape = MaterialTheme.shapes.large,
                        colors = ButtonDefaults.buttonColors(containerColor = VarnikaAccent, contentColor = VarnikaPrimary)
                    ) {
                        Icon(Icons.Rounded.AutoAwesome, contentDescription = null)
                        Spacer(Modifier.width(8.dp))
                        Text("Generate Preview", style = MaterialTheme.typography.titleMedium)
                    }
                }
            }
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier.fillMaxSize().padding(innerPadding).verticalScroll(rememberScrollState())
        ) {
            if (isGenerating) {
                Box(modifier = Modifier.fillMaxWidth().height(300.dp), contentAlignment = Alignment.Center) {
                    CircularProgressIndicator(color = VarnikaAccent)
                    Spacer(modifier = Modifier.height(16.dp))
                    Text("Generating custom design...", color = VarnikaSecondaryAccent, modifier = Modifier.padding(top = 64.dp))
                }
            } else if (hasGenerated) {
                BeforeAfterSlider(
                    beforeImage = R.drawable.img_room_before_1781688663187,
                    afterImage = R.drawable.img_room_after_1781688680567, // Using after image as proxy for generated
                    modifier = Modifier.fillMaxWidth().height(300.dp)
                )
                
                Column(modifier = Modifier.padding(24.dp)) {
                    Text("Your Custom Room", style = MaterialTheme.typography.headlineMedium, color = VarnikaText)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Here is your room redesigned with a $selectedStyle $selectedFurniture in the $selectedBudget range.", color = VarnikaSecondaryAccent, style = MaterialTheme.typography.bodyMedium)
                    Spacer(modifier = Modifier.height(24.dp))
                    Button(onClick = { hasGenerated = false }, modifier = Modifier.fillMaxWidth().height(56.dp), colors = ButtonDefaults.buttonColors(containerColor = VarnikaSecondary, contentColor = VarnikaText), shape = MaterialTheme.shapes.large) {
                        Text("Re-customize")
                    }
                }
            } else {
                // Interactive Designer Options
                Card(colors = CardDefaults.cardColors(containerColor = VarnikaSecondary), modifier = Modifier.fillMaxWidth().padding(16.dp)) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("1. Select Focus Furniture", style = MaterialTheme.typography.titleMedium, color = VarnikaText)
                        Spacer(modifier = Modifier.height(12.dp))
                        LazyRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            items(furnitureOptions) { option ->
                                FilterChip(
                                    selected = selectedFurniture == option,
                                    onClick = { selectedFurniture = option },
                                    label = { Text(option) },
                                    colors = FilterChipDefaults.filterChipColors(selectedContainerColor = VarnikaAccent, selectedLabelColor = VarnikaPrimary, labelColor = VarnikaSecondaryAccent)
                                )
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(24.dp))
                        Text("2. Select Interior Style", style = MaterialTheme.typography.titleMedium, color = VarnikaText)
                        Spacer(modifier = Modifier.height(12.dp))
                        LazyRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            items(styleOptions) { option ->
                                FilterChip(
                                    selected = selectedStyle == option,
                                    onClick = { selectedStyle = option },
                                    label = { Text(option) },
                                    colors = FilterChipDefaults.filterChipColors(selectedContainerColor = VarnikaAccent, selectedLabelColor = VarnikaPrimary, labelColor = VarnikaSecondaryAccent)
                                )
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(24.dp))
                        Text("3. Select Budget", style = MaterialTheme.typography.titleMedium, color = VarnikaText)
                        Spacer(modifier = Modifier.height(12.dp))
                        LazyRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            items(budgetOptions) { option ->
                                FilterChip(
                                    selected = selectedBudget == option,
                                    onClick = { selectedBudget = option },
                                    label = { Text(option) },
                                    colors = FilterChipDefaults.filterChipColors(selectedContainerColor = VarnikaAccent, selectedLabelColor = VarnikaPrimary, labelColor = VarnikaSecondaryAccent)
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}
